### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [AlexBuccheri/fortran_kmeans#1]
I suggest adding the topics `kmeans`, `clustering`, `statistics` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by AlexBuccheri** [comment]
Hi @Beliavsky this is just a repo for fast prototyping, whilst also trying out the Fortuno test framework. It could as well be private. As such, I'm not worried about it being searchable or usable (yet). With that said, I still added some suggested tags. Thanks for the interest.
