### ISSUE TITLE
CMake grill!

### ISSUE THREAD

**Issue by LecrisUT** [AlexBuccheri/fortran_kmeans#2]
https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L6-L8
Only [CMAKE_Fortran_MODULE_DIRECTORY](https://cmake.org/cmake/help/latest/variable/CMAKE_Fortran_MODULE_DIRECTORY.html) should be initialized. The rest are not proper CMake variables, and also can interfere with windows builds

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L11-L27
https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L34-L37

Do not set flags manually, and especially do not edit `CMAKE_Fortran_FLAGS`. Use target flags if you must, but preferably only set it in a preset/CI etc.

Also specifically:
- `-fopenmp` is already resolved by `target_link_libraries(PRIVATE OpenMP::OpenMP_Fortran)`
- `-cpp` CMake has its own process for handling pre-process
- `-Wall` don't add this to everyone, only to devs (CI)
- `-Ox` Usually handled by defaults, but actually `-O0` is a good one for `Debug` since it doesn't specify one by default which is often `-O2` then, but it still should not be hardcoded (user does not have a way to opt-out)
- `-fbacktrace` isn't it implicit with `-g`?

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L66-L67

No, there is a target `MPI::MPI_Fortran` or whatever.

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L47-L52

A good example why the above is important, those flags are propagated to `fortuno`

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L55-L56

Great choice, please use it :D

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L141-L155

Add the test name to `add_test(COMMAND)` so that it can have an effect. Or have no filter and always run the tests.

---

https://github.com/AlexBuccheri/fortran_kmeans/blob/eeeb776fb7cd162126647d4583d7bf529f15320b/CMakeLists.txt#L116

This can be either an `INTERFACE` target (if it's used only once, otherwise you have duplicate source rules), or `OBJECT` library so that it does not actually create a library artifact.

---

Other notes:
- You have the project as a `src-layout`, split the `CMakeLists.txt` in there as well
- What's up with `run.f90`?
- I've only commented on the build part. There are still packaging and CMake design tips

**Comment by AlexBuccheri** [comment]
This issue was resolved with PR #3
